<?php
/**
 * @file
 * Code for the Events feature.
 */

include_once 'hr_events.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_events_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_events';
  $feature->name = t('Events');
  $feature->description = t('Provide events to your space.');
  $feature->components = array(
    'node' => array(
      'hr_event',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle($entity, $entity_id, $entity_type, $features)
 */
function hr_events_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  if (isset($features['hr_events'])) {
    $mlid = og_menu_single_get_link_mlid('node', $entity_id);
    if (empty($features['hr_events'])) {
      menu_link_delete(NULL, 'node/'.$entity_id.'/events');
    }
    else {
      // See if menu link already exists
      $menu_link = menu_link_get_preferred('node/'.$entity_id.'/events', OG_MENU_SINGLE_MENU_NAME);
      if (empty($menu_link)) {
        $menu_link = array(
          'link_path' => 'node/'.$entity_id.'/events',
          'link_title' => 'Events',
          'menu_name' => OG_MENU_SINGLE_MENU_NAME,
          'weight' => 4,
          'plid' => $mlid,
        );
        menu_link_save($menu_link);
      }
    }
  }

}

